---
- name: Dynamic IP Pool for hosts
  hosts: echipamente
  become: true

  vars:
     lista_ip:
        - 1.1.1.1
        - 2.2.2.2
        - 3.3.3.3
        - 4.4.4.4
        - 5.5.5.5
        - 6.6.6.6
     index: "{{ groups.echipamente.index(inventory_hostname) }}"

  tasks:

     - name: Print mesaj
       ansible.builtin.debug:
          msg: "Adresa IP a hostului este {{ lista_ip[index|int] }}"
